routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//
//    return view('welcome');
//})->name('welcome');

Route::get('/','FrontendController@index')->name('welcome');

//Route::get('/products', function () {
//
//return view('frontend.products');
//})->name('products');

Route::get('/products/{category}/{subCategory?}', 'FrontendController@products')->name('products.list');

//Route::get('/product-details', function () {
//
//    return view('frontend.product-details');
//})->name('product_details');

Route::get('/product-details/{product}', 'FrontendController@productDetails')->name('product.details');




Route::get('/checkout', function () {

    return view('frontend.checkout');
})->name('products.checkout');



Route::post('/add_to_cart', 'CartController@addToCart')->name('add_to_cart');

Route::get('/shopping-bag', 'CartController@getProductsFromCart')->name('shopping_bag');
Route::post('/remove_From_cart', 'CartController@removeFromCart')->name('remove_From_cart');








Auth::routes(['register' => true]);

//Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::group(['middleware'=>['auth'], 'prefix'=>'admin'], function () {

    Route::get('/dashboard', function () {
        return view('backend.dashboard');
    })->name('admin.index');

    Route::get('/ad/login', function () {
        return view('backend.login');
    })->name('admin.login');

    Route::get('/ad/register', function () {
        return view('backend.register');
    })->name('admin.register');

    Route::get('/admin/forgot-password', function () {
        return view('backend.forgot-password');
    })->name('forgot-password');

    Route::get('/404', function () {
        return view('backend.404');
    })->name('404');

    Route::get('/blank', function () {
        return view('backend.blank');
    })->name('blank');

    Route::get('/charts', function () {
        return view('backend.charts');
    })->name('charts');

    Route::get('/tables', function () {
        return view('backend.tables');
    })->name('tables');

    Route::get('/buttons', function () {
        return view('backend.buttons');
    })->name('buttons');

    Route::get('/cards', function () {
        return view('backend.cards');
    })->name('cards');

    Route::get('/utilities-color', function () {
        return view('backend.utilities-color');
    })->name('utilities-color');

    Route::get('/utilities-border', function () {
        return view('backend.utilities-border');
    })->name('utilities-border');

    Route::get('/utilities-animation', function () {
        return view('backend.utilities-animation');
    })->name('utilities-animation');

    Route::get('/utilities-other', function () {
        return view('backend.utilities-other');
    })->name('utilities-other');




Route::get('/my-profile', 'UserController@myProfile')->name('my_profile');
Route::get('/users/{id}/edit', 'UserController@edit')->name('users.edit');
Route::put('/users/{id}', 'UserController@update')->name('users.update');

//Route::get('/categories', 'CategoryController@index')->name('categories.index');
//
//Route::get('/categories/create', 'CategoryController@create')->name('categories.create');
//
//Route::post('/categories', 'CategoryController@store')->name('categories.store');
//
//Route::get('/categories/{category}', 'CategoryController@show')->name('categories.show');
//
//Route::get('/categories/{category}/edit', 'CategoryController@edit' )->name('categories.edit');
//
//Route::put('/categories/{category}', 'CategoryController@update')->name('categories.update');
//
//Route::delete('/categories/{category}', 'CategoryController@destroy')->name('categories.destroy');
    Route::resource('categories', 'CategoryController');
    Route::resource('sub-categories', 'SubCategoryController');





    Route::get('/products/pdf', 'PdfController@products')->name('products.pdf');
    Route::get('/products/excel', 'ExcelController@products')->name('products.excel');




    Route::get('/products/trash', 'TrashController@trash')->name('products.trash');
    Route::get('/products/trash/{id}', 'TrashController@showTrash')->name('products.trash_show');
    Route::put('/products/trash/{id}', 'TrashController@restoreTrash')->name('products.trash_restore');
    Route::delete('/products/trash/{id}', 'TrashController@deleteTrash')->name('products.trash_delete');


//Route::get('/products', 'ProductController@index')->name('products.index');
//
//Route::get('/products/create', 'ProductController@create')->name('products.create');
//
//Route::post('/products', 'ProductController@store')->name('products.store');
//
//Route::get('/products/{product}', 'ProductController@show')->name('products.show');
//
//Route::get('/products/{product}/edit', 'ProductController@edit' )->name('products.edit');
//
//Route::put('/products/{product}', 'ProductController@update')->name('products.update');
//
//Route::delete('/products/{product}', 'ProductController@destroy')->name('products.destroy');

    Route::resource('products', 'ProductController');
//    Route::get('color/test', 'ColorController@test');
    Route::resource('colors', 'ColorController');
    Route::resource('sizes', 'SizeController');
    Route::resource('brands', 'BrandController');
    Route::resource('tags', 'TagController');
    Route::resource('blogs', 'BlogController');
    Route::get('products/{product}/{notification}', 'ProductController@show')->name('products.notification');
    Route::post('products/{product}/comment', 'CommentController@productComment')->name('products.comment');

});

//Route::post('products/{product}/comment', 'CommentController@productComment')->name('products.comment');







//Auth::routes();
//
//Route::get('/home', 'HomeController@index')->name('home');

resources/views/backend/layouts/partials/footer.blade.php
<!-- Footer -->
<footer class="sticky-footer bg-white">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
            <span>Copyright &copy; Your Website 2019</span>
        </div>
    </div>
</footer>
<!-- End of Footer -->

resources/views/backend/layouts/partials/header.blade.php
<!-- Topbar -->
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>

    <!-- Topbar Search -->
    <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
        <div class="input-group">
            <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
            <div class="input-group-append">
                <button class="btn btn-primary" type="button">
                    <i class="fas fa-search fa-sm"></i>
                </button>
            </div>
        </div>
    </form>

    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">

        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
        <li class="nav-item dropdown no-arrow d-sm-none">
            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
            </a>
            <!-- Dropdown - Messages -->
            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
                <form class="form-inline mr-auto w-100 navbar-search">
                    <div class="input-group">
                        <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="button">
                                <i class="fas fa-search fa-sm"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </li>

        <!-- Nav Item - Alerts -->
        <li class="nav-item dropdown no-arrow mx-1">
            <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-bell fa-fw"></i>
                <!-- Counter - Alerts -->
                <span class="badge badge-danger badge-counter">{{count(auth()->user()->unreadNotifications)}}</span>
            </a>
            <!-- Dropdown - Alerts -->
            <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="alertsDropdown">
                <h6 class="dropdown-header">
                    Alerts Center
                </h6>
                @if(count(auth()->user()->notifications)>0)

                @foreach(auth()->user()->notifications as $notification)

                <a class="dropdown-item d-flex align-items-center" href="{{route('products.notification', [$notification->data['product_id'],$notification])}}">
                    <div class="mr-3">
                        <div class="icon-circle bg-primary">
                            <i class="fas fa-file-alt text-white"></i>
                        </div>
                    </div>
                    <div>
                        <div class="small text-gray-500">{{$notification->created_at->toFormattedDateString()}}  {{$notification->created_at->DiffForHumans()}}</div>
                        <span class="font-weight-bold">{{$notification->type}}</span>
                    </div>
                </a>
                @endforeach
                @endif
                <a class="dropdown-item text-center small text-gray-500" href="#">Show All Alerts</a>
            </div>
        </li>

        <!-- Nav Item - Messages -->
        <li class="nav-item dropdown no-arrow mx-1">
            <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-envelope fa-fw"></i>
                <!-- Counter - Messages -->
                <span class="badge badge-danger badge-counter">7</span>
            </a>
            <!-- Dropdown - Messages -->
            <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="messagesDropdown">
                <h6 class="dropdown-header">
                    Message Center
                </h6>
                <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="dropdown-list-image mr-3">
                        <img class="rounded-circle" src="https://source.unsplash.com/fn_BT9fwg_E/60x60" alt="">
                        <div class="status-indicator bg-success"></div>
                    </div>
                    <div class="font-weight-bold">
                        <div class="text-truncate">Hi there! I am wondering if you can help me with a problem I've been having.</div>
                        <div class="small text-gray-500">Emily Fowler · 58m</div>
                    </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="dropdown-list-image mr-3">
                        <img class="rounded-circle" src="https://source.unsplash.com/AU4VPcFN4LE/60x60" alt="">
                        <div class="status-indicator"></div>
                    </div>
                    <div>
                        <div class="text-truncate">I have the photos that you ordered last month, how would you like them sent to you?</div>
                        <div class="small text-gray-500">Jae Chun · 1d</div>
                    </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="dropdown-list-image mr-3">
                        <img class="rounded-circle" src="https://source.unsplash.com/CS2uCrpNzJY/60x60" alt="">
                        <div class="status-indicator bg-warning"></div>
                    </div>
                    <div>
                        <div class="text-truncate">Last month's report looks great, I am very happy with the progress so far, keep up the good work!</div>
                        <div class="small text-gray-500">Morgan Alvarez · 2d</div>
                    </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="dropdown-list-image mr-3">
                        <img class="rounded-circle" src="https://source.unsplash.com/Mv9hjnEUHR4/60x60" alt="">
                        <div class="status-indicator bg-success"></div>
                    </div>
                    <div>
                        <div class="text-truncate">Am I a good boy? The reason I ask is because someone told me that people say this to all dogs, even if they aren't good...</div>
                        <div class="small text-gray-500">Chicken the Dog · 2w</div>
                    </div>
                </a>
                <a class="dropdown-item text-center small text-gray-500" href="#">Read More Messages</a>
            </div>
        </li>

        <div class="topbar-divider d-none d-sm-block"></div>

        <!-- Nav Item - User Information -->
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small"> {{auth::user()->name}} </span>
{{--                <img class="img-profile rounded-circle" src="https://source.unsplash.com/QAB-WJcbgJk/60x60">--}}
                @isset(auth()->user()->profile->picture)
                    @if(file_exists(storage_path().'/app/public/users/'.auth()->user()->profile->picture) && (!is_null(auth()->user()->profile->picture)))
                        <img class="img-profile rounded-circle" src="{{ asset('storage/users/'.auth()->user()->profile->picture) }}" height="100">
                    @else
                        <img class="img-profile rounded-circle" src="{{ asset('/default-avatar.png') }}">
                    @endif
                @else
                    <img class="img-profile rounded-circle" src="{{ asset('/default-avatar.png') }}">
                @endisset

            </a>
            <!-- Dropdown - User Information -->
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="{{route('my_profile')}}">
                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                    Profile
                </a>
                <a class="dropdown-item" href="#">
                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                    Settings
                </a>
                <a class="dropdown-item" href="#">
                    <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                    Activity Log
                </a>
                <div class="dropdown-divider"></div>
{{--                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">--}}
{{--                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>--}}
{{--                    Logout--}}
{{--                </a>--}}
                <a class="dropdown-item" href="{{ route('logout') }}"
                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                    {{ __('Logout') }}
                </a>

                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    @csrf
                </form>
            </div>
        </li>

    </ul>

</nav>
<!-- End of Topbar -->

resources/views/backend/layouts/partials/sidebar.blade.php
<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
        <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">E-Commerce App</div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item active">
        <a class="nav-link" href="{{route('admin.index')}}">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>{{auth()->user()->role->name}} Dashboard</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        Interface
    </div>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
            <i class="fas fa-fw fa-product-hunt"></i>
            <span>Products</span>
        </a>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Product Modules:</h6>
                <a class="collapse-item"  href="{{ route('categories.index') }}">Categories</a>
                <a class="collapse-item"  href="{{ route('sub-categories.index') }}">Sub-Categories</a>

                <a class="collapse-item" href="{{route('products.index')}}">Products</a>
                <a class="collapse-item" href="{{route('brands.index')}}">Brands</a>
                <a class="collapse-item" href="{{route('sizes.index')}}">Sizes</a>
                <a class="collapse-item" href="{{route('colors.index')}}">Colors</a>
                <a class="collapse-item" href="{{route('tags.index')}}">Tags</a>
{{--                <a class="collapse-item" href="{{route('blogs.index')}}">Blogs</a>--}}
            </div>
        </div>
    </li>
    <!-- Nav Item - Blogs -->
    <li class="nav-item">
        <a class="nav-link" href="{{route('blogs.index')}}">
            <i class="fas fa-fw fa-blog"></i>
            <span>Blogs</span></a>
    </li>

    <!-- Nav Item - Utilities Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities" aria-expanded="true" aria-controls="collapseUtilities">
            <i class="fas fa-fw fa-wrench"></i>
            <span>Utilities</span>
        </a>
        <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Custom Utilities:</h6>
                <a class="collapse-item" href="{{route('utilities-color')}}">Colors</a>
                <a class="collapse-item" href="{{route('utilities-border')}}">Borders</a>
                <a class="collapse-item" href="{{route('utilities-animation')}}">Animations</a>
                <a class="collapse-item" href="{{route('utilities-other')}}">Other</a>
            </div>
        </div>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        Addons
    </div>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="true" aria-controls="collapsePages">
            <i class="fas fa-fw fa-folder"></i>
            <span>Pages</span>
        </a>
        <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Login Screens:</h6>
                <a class="collapse-item" href="{{route('admin.login')}}">Login</a>
                <a class="collapse-item" href="{{route('admin.register')}}">Register</a>
                <a class="collapse-item" href="{{route('forgot-password')}}">Forgot Password</a>
                <div class="collapse-divider"></div>
                <h6 class="collapse-header">Other Pages:</h6>
                <a class="collapse-item" href="{{route('404')}}">404 Page</a>
                <a class="collapse-item" href="{{route('blank')}}">Blank Page</a>
            </div>
        </div>
    </li>

    <!-- Nav Item - Charts -->
    <li class="nav-item">
        <a class="nav-link" href="{{route('charts')}}">
            <i class="fas fa-fw fa-chart-area"></i>
            <span>Charts</span></a>
    </li>



    <!-- Nav Item - Tables -->
    <li class="nav-item">
        <a class="nav-link" href="{{route('tables')}}">
            <i class="fas fa-fw fa-table"></i>
            <span>Tables</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

</ul>
<!-- End of Sidebar -->