routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//
//    return view('welcome');
//})->name('welcome');

Route::get('/','FrontendController@index')->name('welcome');

//Route::get('/products', function () {
//
//return view('frontend.products');
//})->name('products');

Route::get('/products/{category}/{subCategory?}', 'FrontendController@products')->name('products.list');

//Route::get('/product-details', function () {
//
//    return view('frontend.product-details');
//})->name('product_details');

Route::get('/product-details/{product}', 'FrontendController@productDetails')->name('product.details');




Route::get('/checkout', function () {

    return view('frontend.checkout');
})->name('products.checkout');



Route::post('/add_to_cart', 'CartController@addToCart')->name('add_to_cart');

Route::get('/shopping-bag', 'CartController@getProductsFromCart')->name('shopping_bag');
Route::post('/remove_From_cart', 'CartController@removeFromCart')->name('remove_From_cart');








Auth::routes(['register' => true]);

//Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::group(['middleware'=>['auth'], 'prefix'=>'admin'], function () {

    Route::get('/dashboard', function () {
        return view('backend.dashboard');
    })->name('admin.index');

    Route::get('/ad/login', function () {
        return view('backend.login');
    })->name('admin.login');

    Route::get('/ad/register', function () {
        return view('backend.register');
    })->name('admin.register');

    Route::get('/admin/forgot-password', function () {
        return view('backend.forgot-password');
    })->name('forgot-password');

    Route::get('/404', function () {
        return view('backend.404');
    })->name('404');

    Route::get('/blank', function () {
        return view('backend.blank');
    })->name('blank');

    Route::get('/charts', function () {
        return view('backend.charts');
    })->name('charts');

    Route::get('/tables', function () {
        return view('backend.tables');
    })->name('tables');

    Route::get('/buttons', function () {
        return view('backend.buttons');
    })->name('buttons');

    Route::get('/cards', function () {
        return view('backend.cards');
    })->name('cards');

    Route::get('/utilities-color', function () {
        return view('backend.utilities-color');
    })->name('utilities-color');

    Route::get('/utilities-border', function () {
        return view('backend.utilities-border');
    })->name('utilities-border');

    Route::get('/utilities-animation', function () {
        return view('backend.utilities-animation');
    })->name('utilities-animation');

    Route::get('/utilities-other', function () {
        return view('backend.utilities-other');
    })->name('utilities-other');




Route::get('/my-profile', 'UserController@myProfile')->name('my_profile');
Route::get('/users/{id}/edit', 'UserController@edit')->name('users.edit');
Route::put('/users/{id}', 'UserController@update')->name('users.update');

//Route::get('/categories', 'CategoryController@index')->name('categories.index');
//
//Route::get('/categories/create', 'CategoryController@create')->name('categories.create');
//
//Route::post('/categories', 'CategoryController@store')->name('categories.store');
//
//Route::get('/categories/{category}', 'CategoryController@show')->name('categories.show');
//
//Route::get('/categories/{category}/edit', 'CategoryController@edit' )->name('categories.edit');
//
//Route::put('/categories/{category}', 'CategoryController@update')->name('categories.update');
//
//Route::delete('/categories/{category}', 'CategoryController@destroy')->name('categories.destroy');
    Route::resource('categories', 'CategoryController');
    Route::resource('sub-categories', 'SubCategoryController');





    Route::get('/products/pdf', 'PdfController@products')->name('products.pdf');
    Route::get('/products/excel', 'ExcelController@products')->name('products.excel');




    Route::get('/products/trash', 'TrashController@trash')->name('products.trash');
    Route::get('/products/trash/{id}', 'TrashController@showTrash')->name('products.trash_show');
    Route::put('/products/trash/{id}', 'TrashController@restoreTrash')->name('products.trash_restore');
    Route::delete('/products/trash/{id}', 'TrashController@deleteTrash')->name('products.trash_delete');


//Route::get('/products', 'ProductController@index')->name('products.index');
//
//Route::get('/products/create', 'ProductController@create')->name('products.create');
//
//Route::post('/products', 'ProductController@store')->name('products.store');
//
//Route::get('/products/{product}', 'ProductController@show')->name('products.show');
//
//Route::get('/products/{product}/edit', 'ProductController@edit' )->name('products.edit');
//
//Route::put('/products/{product}', 'ProductController@update')->name('products.update');
//
//Route::delete('/products/{product}', 'ProductController@destroy')->name('products.destroy');

    Route::resource('products', 'ProductController');
//    Route::get('color/test', 'ColorController@test');
    Route::resource('colors', 'ColorController');
    Route::resource('sizes', 'SizeController');
    Route::resource('brands', 'BrandController');
    Route::resource('tags', 'TagController');
    Route::resource('blogs', 'BlogController');
    Route::get('products/{product}/{notification}', 'ProductController@show')->name('products.notification');
    Route::post('products/{product}/comment', 'CommentController@productComment')->name('products.comment');

});

//Route::post('products/{product}/comment', 'CommentController@productComment')->name('products.comment');







//Auth::routes();
//
//Route::get('/home', 'HomeController@index')->name('home');

app/Color.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Color extends Model
{
    protected $fillable=['name', 'created_by', 'updated_by'];

    public function products()
    {
        return $this->belongsToMany(Product::class);
    }
    public function createdBy()
    {
        return $this->belongsTo(User::class, 'created_by');
    }
    public function updatedBy()
    {
        return $this->belongsTo(User::class, 'updated_by');
    }
}

app/Http/Controllers/ColorController.php
<?php

namespace App\Http\Controllers;


use App\Color;

use App\User;
use Illuminate\Database\QueryException;
use Illuminate\Http\Request;

class ColorController extends Controller
{
    public function index()
    {

        $sl = !is_null(\request()->page) ? (\request()->page-1) * 10 : 0;
        $colors =Color::orderBy('created_at','desc')->paginate(10);

        return view('backend.colors.index', compact('colors','sl'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
//        $users = User::pluck('name','id')->toArray();

        return view('backend.colors.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
//        dd($request->all());
        $colors = $request->all();
//        dd($colors);
        try {
            $colors['created_by']=auth()->user()->id;
            Color::create($colors);

            return redirect()->route('colors.index')->withStatus('Created successfully!');
        }catch (QueryException $e){
            return redirect()->back()->withErrors($e->getMessage());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Color $color) //route model model binding/ dependency injection
    {

        return view('backend.colors.show', compact('color'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Color $color)
    {
//        $users = User::pluck('name','id')->toArray();

        return view('backend.colors.edit', compact('color'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Color $color)
    {
        try{
            $request['updated_by']=auth()->user()->id;

            $color->update($request->all());
            return redirect()->route('colors.index')->withStatus('Updated successfully!');
        }catch (QueryException $e){
            return redirect()->back()->withErrors($e->getMessage());
        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Color $color)
    {
        try{
            $color->delete();
            return redirect()->route('colors.index')->withStatus('Delete successfully!');
        }catch (QueryException $e){
            return redirect()->back()->withErrors($e->getMessage());
        }
    }
}

resources/views/backend/colors/create.blade.php
@extends('backend.layouts.master')

@section('title', 'Colors Create')

@section('content')
<div class="container-fluid">

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <div class="row">
                <div class="col-md-6">Create Color</div>
                <div class="col-md-6 text-right">
                    <a href="{{ route('colors.index') }}" class="btn btn-sm btn-outline-primary">List</a>
                </div>
            </div>
        </div>
        <div class="card-body">
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
               {{ Form::open(['route'=>'colors.store',
                          'files'=>true,
                          ])}}
{{--            <form action="{{route('categories.store')}}" method="post">--}}
{{--                @csrf--}}

                @include('backend.colors.form')


{{--               <button class="btn btn-primary" type="submit">Submit form</button>--}}
                   {{Form::button('Submit form',[
                                    'class'=>'btn btn-primary',
                                    'type'=>'submit',
                                       ])}}

{{--            </form>--}}
            {{ Form::close()}}
        </div>
    </div>
</div>
@endsection

resources/views/backend/colors/edit.blade.php
@extends('backend.layouts.master')

@section('title', 'Size Edit')

@section('content')
    <div class="container-fluid">

        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <div class="row">
                    <div class="col-md-6">Edit Size</div>
                    <div class="col-md-6 text-right">
                        <a href="{{ route('sizes.index') }}" class="btn btn-sm btn-outline-primary">List</a>
                    </div>
                </div>
            </div>
            <div class="card-body">
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                {{Form::model($size, [
                      'route'=>['sizes.update',
                      $size->id],
                      'files'=>true,
                      'method'=>'put',
                 ])}}
{{--                <form action="{{route('categories.update', $category->id)}}" method="post">--}}
                    @csrf
                    @method('PUT')

                    @include('backend.sizes.form')

{{--                    <button class="btn btn-primary" type="submit">Submit form</button>--}}
                    {{Form::button('Submit form',[
                                    'class'=>'btn btn-primary',
                                    'type'=>'submit',
                                       ])}}
{{--                </form>--}}
                    {{ Form::close()}}
            </div>
        </div>
    </div>
@endsection

resources/views/backend/colors/form.blade.php
{{--<div class="form-row">--}}
{{--    <div class="col-md-12 mb-3">--}}

{{--        {{Form::label('created_by','CreatedBy')}}<br>--}}
{{--        {{Form::select('created_by',$users, null,--}}
{{--               ["placeholder"=>"Select User"])}}--}}

{{--    </div>--}}
{{--</div>--}}

{{--<div class="form-row">--}}
{{--    <div class="col-md-12 mb-3">--}}

{{--        {{Form::label('updated_by','UpdatedBy')}}<br>--}}
{{--        {{Form::select('updated_by',$users, null,--}}
{{--               ["placeholder"=>"Select User"])}}--}}

{{--    </div>--}}
{{--</div>--}}



<div class="form-row">
<div class="col-md-12 mb-3">
    {{Form::label('name','Colors')}}
    {{Form::text('name', null, [
          'class'=> $errors->has('name') ?  'form-control is-invalid': 'form-control',
          'placeholder'=>'Enter The Color name',
          'id'=>'name',
    ])}}
    @error('name')
    <div class="text-danger">{{ $message }}</div>
    @enderror

    </div>
</div>

{{--<div class="form-row">--}}
{{--    <div class="col-md-12 mb-3">--}}

{{--        {{Form::label('created_by','CreatedBy')}}<br>--}}
{{--        {{Form::select('created_by',$users, null,--}}
{{--               ["placeholder"=>"Select User"])}}--}}

{{--    </div>--}}
{{--</div>--}}
{{--@error('created_by')--}}
{{--<div class="text-danger">{{ $message }}</div>--}}
{{--@enderror--}}



{{--<div class="form-row">--}}
{{--<div class="col-md-12 mb-3">--}}

{{--    {{Form::label('updated_by','UpdatedBy')}}<br>--}}
{{--    {{Form::select('updated_by',$users, null,--}}
{{--           ["placeholder"=>"Select User"])}}--}}

{{--</div>--}}
{{--</div>--}}
{{--@error('updated_by')--}}
{{--<div class="text-danger">{{ $message }}</div>--}}
{{--@enderror--}}

resources/views/backend/colors/index.blade.php
@extends('backend.layouts.master')

@section('title', 'Colors')

@section('content')
<div class="container-fluid">

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <div class="row">
                <div class="col-md-6">Colors</div>
                <div class="col-md-6 text-right">
                    <a href="{{ route('colors.create') }}" class="btn btn-sm btn-outline-primary">Add New</a>

                </div>
            </div>
        </div>
        <div class="card-body">
            <div class="table-responsive">
{{--                id="dataTable"--}}
                <table class="table table-bordered"  width="100%" cellspacing="0">
                    <thead>
                    <tr>
                        <th>#SL</th>
                        <th>Colors</th>

                        <th>CreatedBy</th>
                        <th>UpdatedBy</th>
                        <th style="width: 150px; text-align: center;">Action</th>
                    </tr>
                    </thead>
                    <tbody>

                    @if(session()->has('status'))
                     <div class="alert alert-success">

                            <p>{{session('status')}}</p>

                     </div>
                    @endif

                    @foreach($colors as $color)
                    <tr>
                        <td>{{++$sl}}</td>

                        <td>{{$color->name}}</td>

                        <td>{{$color->createdBy->name??null}}</td>
                        <td>{{$color->updatedBy->name??null}}</td>
                        <td>
                            <a href="{{ route('colors.show', $color->id) }}" class="btn btn-sm btn-outline-info">Show</a>
                            <a href="{{ route('colors.edit', $color->id) }}" class="btn btn-sm btn-outline-warning">Edit</a>
{{--                            <a href="#" class="btn btn-sm btn-outline-danger">Delete</a>--}}
                            <form action="{{route('colors.destroy', $color->id)}}" method="post">
                                @csrf
                                @method('DELETE')
                                <button style="background-color: darkred;" type="submit" onclick="return confirm('Are you sure Want to delete?')">Delete</button>

                            </form>


                        </td>
                    </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
            {{ $colors->links() }}
        </div>

    </div>

</div>
@endsection

@push('css')
    <!-- Custom styles for this page -->
    <link href="{{ asset('ui/backend') }}/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">
@endpush

@push('script')
    <!-- Page level plugins -->
    <script src="{{ asset('ui/backend') }}/vendor/datatables/jquery.dataTables.min.js"></script>
    <script src="{{ asset('ui/backend') }}/vendor/datatables/dataTables.bootstrap4.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="{{ asset('ui/backend') }}/js/demo/datatables-demo.js"></script>
@endpush

resources/views/backend/colors/show.blade.php
@extends('backend.layouts.master')

@section('title', 'Colors Details')

@section('content')
    <div class="container-fluid">

        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <div class="row">
                    <div class="col-md-6">Show Color</div>
                    <div class="col-md-6 text-right">
                        <a href="{{ route('colors.index') }}" class="btn btn-sm btn-outline-primary">List</a>
                    </div>
                </div>
            </div>
            <div class="card-body">

                <table class="table table-striped">
                    <tbody>
                    <tr>
                        <th>Color</th>
                        <th>{{ $color->name }}</th>
                    </tr>
                    <tr>
                        <th>CreatedBy</th>
                        <th>{{ $color->createdBy->name??null }}</th>
                    </tr>
                    <tr>
                        <th>UpdatedBy</th>
                        <th>{{ $color->updatedBy->name??null }}</th>
                    </tr>

                    </tbody>
                </table>
            </div>
        </div>

    </div>
@endsection